config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :quiz, :users, :sessions

  root 'quiz#index'

end

app/models/square.rb
class Square < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  # protect_from_forgery with: :exception
  protect_from_forgery wih: :null_session
  include SessionsHelper
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  def index
  	@squares = Square.all
  	# @lastSquare = params[:s_field]
  	# @answer = params[:a_field]
  	# @color = params[:col_field]
  	# @image = params[:img_field]
  end

  def show
  	@lastSquare = params[:s_field]
  	@answer = params[:a_field]
  	@color = params[:col_field]
  	@image = params[:img_field]

    # if @answer == "correct"
      # add one to number of correct quesses for current user
    #else
      # add one to number of incorrect quesses for current user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username:params[:username].downcase)
    if @user && @user.authenticate(params[:password])
      log_in @user
      redirect_to root_path
    else
      redirect_to new_user_path, alert: "Error"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(username:params[:username],password:params[:password])
    if @user.save
      log_in @user
      redirect_to root_path
    else
      redirect_to new_user_path, alert: "Error"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
	def squareAnswerWhite(square)
		if square.color == 'light square'
			return 'correct'
		else
			return 'incorrect'
		end
	end

	def squareAnswerBlack(square)
		if square.color == 'dark square'
			return 'correct'
		else
			return 'incorrect'
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def log_out
    session.delete(:user_id)
    current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisualizeSquare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="topbar">

    <div id="logo">
      <p>marksman</p>
    </div>

    <div id="login">

    <% if !logged_in? %>

    <%= form_tag("/sessions", method:"post") do %>

      <%= text_field_tag :username %>
      <%= password_field_tag :password %>

      <%= submit_tag "Login" %>

    <% end %>

    <% else %>

    <p><%= current_user.username %>

      <%= button_to "Log Out", session_path(session[:user_id]), :method => :delete %>
    </p>



    <% end %>

    </div>

    <div id="links">

      <p> <%= link_to "Home", quiz_index_url %>

      <% if !logged_in? %>

        | <%= link_to "Register", users_new_url %> </p>

      <% end %>

    </div>

  </div>

<%= yield %>

</body>
</html>

app/views/quiz/index.html.erb
<div class="center" id="notation">
  <% @square = @squares.shuffle.first %>
  <h1><%= @square.coord %></h1>
</div>

<% @white = squareAnswerWhite(@square) %>
<% @black = squareAnswerBlack(@square) %>

<div class="center" id="light-button">
  <%= button_to "Light Square", quiz_path(1), :method => "get", params: {a_field: @white, s_field: @square.coord, col_field: @square.color, img_field: @square.image} %>
</div>
<div class="center" id="dark-button">
  <%= button_to "Dark Square", quiz_path(1), :method => "get", params: {a_field: @black, s_field: @square.coord, col_field: @square.color, img_field: @square.image} %>
</div>

app/views/quiz/show.html.erb
<div id="results">
	<% if @lastSquare && @answer && @color %>
		<p>
		<strong><%= @lastSquare %></strong> is a <%= @color %> which you got
			<% if @answer == "correct"%>
				<span id="correct"><%= @answer %></span>
			<% else %>
				<span id="incorrect"><%= @answer %></span>
			<% end %>
		</p>
		<img src='../<%= @image %>'/>
	<% end %>

	<%= button_to "next question", root_path, :method => "get" %>
</div>

app/views/users/new.html.erb
<form action="/users" method="post">

  <input type="textarea" placeholder="username" name="username">

  <input type="password" placeholder="password" name="password">

  <button type="submit">Join</button>

</form>